### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by viniciusreiss** [dlourennco/WeTime#4]
Cara seu código deve ser autoexplicativo, escrever comentários não é uma boa prática no código.
`
    let locationTimezone = document.querySelector('.location-timezone');
    

> //pega a localização

`
Exemplo: 
`
    let getLocationTimezone = document.querySelector('.location-timezone');
`

**Comment by dlourennco** [comment]
Removi os comentários a alguns commits, realmente ajuda a ler o código muito mais rápido! Obrigado.
